version: "3.8"

services:
  webserver:
    image: php:8.2-apache
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      - ./logs/apache2:/var/log/apache2
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    depends_on:
      - database
    command: >
      bash -c "
      docker-php-ext-install mysqli pdo pdo_mysql &&
      a2enmod rewrite &&
      apache2-foreground
      "
    labels:
      - "coolify.managed=true"
      - "coolify.http.enabled=true"
      - "coolify.http.port=80"

  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: tiger
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 512M
    depends_on:
      - database
    labels:
      - "coolify.managed=true"
      - "coolify.http.enabled=true"
      - "coolify.http.port=80"

  redis:
    image: redis:latest
    restart: always
