version: "3.8"

services:
  webserver:
    image: php:8.2-apache
    container_name: "lamp-webserver"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html:rw
      - ./logs/apache2:/var/log/apache2
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
    depends_on:
      - database
    command: >
      bash -c "
      docker-php-ext-install mysqli pdo pdo_mysql &&
      a2enmod rewrite &&
      apache2-foreground
      "

  database:
    image: mysql:8.0
    container_name: "lamp-database"
    restart: always
    # No external port - only internal access
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "lamp-phpmyadmin"
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: tiger
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 512M
    depends_on:
      - database

  redis:
    image: redis:latest
    container_name: "lamp-redis"
    restart: always
    ports:
      - "6379:6379"
